### ISSUE TITLE
Send temperature from external sensor and pull load values from TRV

### ISSUE THREAD

**Issue by markdybdal** [MTrab/danfoss_ally#1]
Hi
It would be great it you could implement an option to send temperature from an external sensor to the Ally TRV by 
0x4015. 

Would it also be possible to pull load and heat demand values (0x0008 & 0x404A) to visualise the load on each radiator?

Otherwise thanks for the great work!

//Mark

**Comment by MTrab** [comment]
There is no such options available in the API
