### ISSUE TITLE
Not able to add integration

### ISSUE THREAD

**Issue by JanSkinnerup** [MTrab/danfoss_ally#10]
I've added this repository and integration in HACS. I've created the Danfoss account and project and got my API key. 
But I get stuck at "Go to Home Assistant > Settings > Integrations and add Danfoss Ally". No such integration shows up. What am I missing? Or where am I supposed to enter my API key and secret?

**Comment by MTrab** [comment]
Did you restart Home Assistant, after installing the integration?

**Comment by JanSkinnerup** [comment]
Yes... several times :-)

**Comment by MTrab** [comment]
And the logs?

**Comment by JanSkinnerup** [comment]
I don't see anything specific for this integration. There is one generic error but I have no idea if its related:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:592
Integration: Sensor (documentation, issues)
First occurred: 16.49.20 (1 occurrences)
Last logged: 16.49.20

Platform hacs does not generate unique IDs. ID 0717a0cd-745c-48fd-9b16-c8534c9704f9-bc944b0f-fd42-4a58-a072-ade38d1444cd already exists - ignoring sensor.hacs

**Comment by MTrab** [comment]
No, that's not related - that's some HACS error.

Well, in that case I can only advice to reinstall the integration and then restart your Home Assistant afterwards.

**Comment by JanSkinnerup** [comment]
Tried that already :-(

**Comment by JanSkinnerup** [comment]
Fixed it. I uninstalled 1.0.3, restarted and then installed 1.0.2 instead. I was then able to add the integration and input my API.
