### ISSUE TITLE
external_sensor_temperature should override current_temperature

### ISSUE THREAD

**Issue by tcarlsen** [MTrab/danfoss_ally#103]
### Describe the issue

If a termostat has an `external_sensor_temperature` this should override the `current_temperature` as this is the new truth

This was also the behavior before the new API  update

![image](https://github.com/MTrab/danfoss_ally/assets/145288/4470f876-64c7-4f16-9ad3-86b685cd35f1)
![image](https://github.com/MTrab/danfoss_ally/assets/145288/deb4d5ad-4e8c-437b-ab4a-cddaa496abd0)

### What version of Home Assistant Core has the issue?

core-2024.2.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

why is this field required?

**Comment by tbarnekov** [comment]
I think this will be fixed by #106
