### ISSUE TITLE
Danfoss Ally Room Sensor

### ISSUE THREAD

**Issue by skarum** [MTrab/danfoss_ally#11]
Hi, 

I just added a Room Sensor to my Ally setup and It also appears in the integration, but it's missing the reported temperature and humidity.

My guess is that the names for the attributes are the problem. This is how the API returns data from the device:

```json
{
    "active_time": 1642951045,
    "create_time": 1642951045,
    "id": "<id>",
    "name": "Danfoss Ally™ Room Sensor",
    "online": true,
    "status": [
      {
        "code": "va_temperature",
        "value": 219
      },
      {
        "code": "va_humidity",
        "value": 468
      },
      {
        "code": "battery_percentage",
        "value": 100
      }
    ],
    "sub": true,
    "time_zone": "+02:00",
    "update_time": 1642951071,
    "device_type": "Danfoss Ally™ Room Sensor"
  }
```

My guess is that `va_temperature` and `va_humidity` need to be translated to `temperature` and  `humidity` to be understood by Home Assistant? Unfortunately, my Python skills are not good enough to know how to do it in a PR.

**Comment by MTrab** [comment]
The integration haven't been prepared for the room sensor as it wasn't available when I started :)
Will look into adding support for the sensor.
