### ISSUE TITLE
Error When Setting Up Integration -  Config flow could not be loaded: {"message":"Invalid handler specified"} 

### ISSUE THREAD

**Issue by luckylinux** [MTrab/danfoss_ally#110]
### Describe the issue

I'm trying to setup the integration with Home Assistant Docker/Podman (IIRC this is called Home Assistant Core).

After the clicking Settings -> Integrations -> Add Integration -> Search for "Ally" -> Click

And the initial message:
```
Please wait, starting configuration wizard for danfoss_ally
```

I get this error:
```
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

### What version of Home Assistant Core has the issue?

2023.12.4

### What type of installation are you running?

Home Assistant Core

### Diagnostics information

None (cannot add the integration)

### Anything in the logs that might be useful for us?

```txt
2024-03-17 15:10:49.028 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration danfoss_ally which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-17 15:10:52.938 ERROR (MainThread) [aiodhcpwatcher] Cannot watch for dhcp packets: [Errno 1] Operation not permitted
2024-03-17 15:12:29.517 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration danfoss_ally: No module named 'pydanfossally'
2024-03-17 15:12:36.402 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration danfoss_ally: No module named 'pydanfossally
```

### Additional information

The error message is pretty self-explanatory. The required Python modules need to be installed, possibly into a venv, by PIP.

However, how to solve this with a (pre-built) Docker Image from Home Assistant it's not.

If I was doing something from scratch, I'd just write a Dockerfile and setup my own venv in there, similarly to what I do in my own projects.

But is there a way to do this when the image is shipped by somebody else (i.e. pre-built) ? Or the only solution is to take their Dockerfile and modify to suit all my needs ?

Thank you for your help :)

**Comment by MTrab** [comment]
HA 2023.12.4 is already pretty outdated, so please update.
Not sure Danfoss Ally integration actually supports usage in 2023.12.4 anymore

**Comment by luckylinux** [comment]
Alright. Weird ... I had pulled home-assistant:stable yesterday just to make sure I was on the latest version.

Now I added pull_policy: "always" in my compose.yml file and it seems to be working.

Now version is `2024.3.1`.

And I am getting asked to provide API key and API secret
![image](https://github.com/MTrab/danfoss_ally/assets/7126291/a7fcd781-ec4f-4618-93bd-fc621c0b3b29)

**Comment by MTrab** [comment]
That is correct - you get that from the developer portal
