### ISSUE TITLE
Unable to communicate after updating to ver. 1.3.4

### ISSUE THREAD

**Issue by DunkeDrengen** [MTrab/danfoss_ally#121]
### Describe the issue

After updating to ver. 1.3.4 all entities is unavailable. Data from the Danfoss app is normal and fully controllable 

### What version of Home Assistant Core has the issue?

core-2024.5.2

### What was the last working version of Home Assistant Core?

core-2024.4

### What type of installation are you running?

Home Assistant OS

### Additional information

Updated Home Assistant Core at the same time, so unsure if it's the core upgrade that "broke" the integration or if it's the ally integration.

**Comment by fazzer4x** [comment]
Why did you close the issue? Did you resolve your problems? I too am facing empty entities.

**Comment by SahnCH** [comment]
Same here

**Comment by DunkeDrengen** [comment]
HI. I closed the issue because i thought i was a local bug - after a complete shutdown of my HA-server, everything was up and running again

**Comment by SahnCH** [comment]
> HI. I closed the issue because i thought i was a local bug - after a complete shutdown of my HA-server, everything was up and running again

Same for me - you're a superstar <3

**Comment by MTrab** [comment]
Danfoss had a server error, was fixed earlier today
