### ISSUE TITLE
Open Windows not being reported in HA

### ISSUE THREAD

**Issue by JanSkinnerup** [MTrab/danfoss_ally#15]
Is it just me or has the open windows detection stopped working?
I know it worked a week or so ago but now it doens't. HA just reports windows as closed no matter what.

I'm pretty sure it works within the Danfoss Ally system as my rediators do not turn on. But for some reason it doesn't get reported to HA.
![Ally02](https://user-images.githubusercontent.com/77300807/154802714-c3aafeb8-b2a1-42a3-b87c-e4366e3af94d.png)
![Ally01](https://user-images.githubusercontent.com/77300807/154802715-5001a7f4-be24-4197-a979-3ace40732804.png)

All other temperature measurements work fine.

**Comment by MTrab** [comment]
Integration is reporting what is received from Danfoss - so not an issue for this integration
