### ISSUE TITLE
Add commandset for setting TRV Mode

### ISSUE THREAD

**Issue by truffles003** [MTrab/danfoss_ally#16]
Been running some tests on the developer page: https://developer.danfoss.com/docs/ally/1/routes/devices/%7Bdevice_id%7D/commands/post

Seems like running other commandset are supported. Tried changing the TRV mode with the following:

`{
  "commands": [
    {
      "code": "mode",
      "value": "at_home"
    }
  ]
}`

`{
  "commands": [
    {
      "code": "mode",
      "value": "pause"
    }
  ]
}`

`{
  "commands": [
    {
      "code": "mode",
      "value": "leaving_home"
    }
  ]
}`

This would make it possible to add your own external schedules.

**Comment by MTrab** [comment]
And these commands work?
I've tried before, but couldn't seem to get it to work - and Danfoss is, as always, silent as the thomb

**Comment by truffles003** [comment]
I see, no response on the trv...

**Comment by MTrab** [comment]
Exactly what I was seeing in my tests.
