### ISSUE TITLE
HA Core 2025.1. Error

### ISSUE THREAD

**Issue by AndersNilsson19** [MTrab/danfoss_ally#188]
### Describe the issue

Logger: homeassistant.components.climate.const
Källa: helpers/deprecation.py:222
integration: Klimat ([dokumentation](https://www.home-assistant.io/integrations/climate), [ärenden](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
Inträffade först: 15:21:08 (7 händelser)
Senast loggade: 15:21:09

CURRENT_HVAC_IDLE was used from danfoss_ally, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please report it to the author of the 'danfoss_ally' custom integration
HVAC_MODE_AUTO was used from danfoss_ally, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please report it to the author of the 'danfoss_ally' custom integration
HVAC_MODE_HEAT was used from danfoss_ally, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'danfoss_ally' custom integration
HVAC_MODE_COOL was used from danfoss_ally, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'danfoss_ally' custom integration
HVAC_MODE_OFF was used from danfoss_ally, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'danfoss_ally' custom integration

Logger: homeassistant.helpers.frame
Källa: helpers/frame.py:324
Inträffade först: 15:20:39 (1 händelser)
Senast loggade: 15:20:39

Detected that custom integration 'danfoss_ally' calls async_forward_entry_setup for integration, danfoss_ally with title: Danfoss Ally and entry_id: 54374a0e85fd69f9426b877bd9ca3210, which is deprecated, await async_forward_entry_setups instead at custom_components/danfoss_ally/__init__.py, line 160: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/MTrab/danfoss_ally/issues

Logger: homeassistant.helpers.frame
Källa: helpers/frame.py:234
Inträffade först: 15:21:09 (5 händelser)
Senast loggade: 15:21:09

Detected code that calls async_forward_entry_setup for integration danfoss_ally with title: Danfoss Ally and entry_id: 54374a0e85fd69f9426b877bd9ca3210, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue

### What version of Home Assistant Core has the issue?

addaada

### What was the last working version of Home Assistant Core?

dadadad

### What type of installation are you running?

Home Assistant OS

**Comment by MTrab** [comment]
Isn't this the same as #153 

Not an error, but a deprecation warning
