### ISSUE TITLE
Integration dont run after updateing to 1.0.6

### ISSUE THREAD

**Issue by thorkildnielsen** [MTrab/danfoss_ally#19]
After installing the last update 1.0.6, and the last HA version The integration dont run.  I have tryed uninstall. reboot and then install again.

I get this message when trying to add the integration againg
![Skærmbillede 2022-04-11 153726](https://user-images.githubusercontent.com/72189386/162751620-8ed3f4c3-50ee-47c9-8ca7-fd3a8d3827ec.jpg)

**Comment by MTrab** [comment]
Fixed in 1.0.7

**Comment by thorkildnielsen** [comment]
Thanks .. Works again... Thanks for a great integration...
