### ISSUE TITLE
Expose current temperatue as a sensor

### ISSUE THREAD

**Issue by cokeman0** [MTrab/danfoss_ally#2]
Would it be possible to expose the current temperature as a sensor ?

I know I can make a sensor template, but would be nice if was a standart in the integration

and 

When grouping 2 allys in 1 room, can that "group" be exposed as in the Ally app ??

**Comment by MTrab** [comment]
It won't make much sense to expose a sensor along side of the climate entity.

What do you mean by the grouping question?

**Comment by cokeman0** [comment]
Ok, I'll just make som "sensors" myself, but I used Tado before going over to Ally, and I used the current temperatur sensor to graph the temperatur in the room, works very nice. But I hope you will reconsider sensor.name_of_device_temperature is very goog for history and visual representation of the temperatur.

Group: in the Ally app you can create a room with 2 Allys (my living room has 2 radiators) and when adding 2 Allys to this room, the Danfoss app makes a "(name of room) group" here you have the same options as on the single device, but adjusting the group to XX degrees are then sent to both/all devices so the have the same setting.

**Comment by MTrab** [comment]
I'm almost 100% sure the API doesn't expose groups.
And I have no way of testing this either, unless you would lend me access to your API.

**Comment by cokeman0** [comment]
og Damm, så er du fra Skanderborg, så behøver vi da ikke engelsk :) 

Jeg har 15 Allys, 2 rum har 2 radiatore, så ville da være fedt hvis man kunne nøjes med at styre gruppen :-) 

Hvordan får jeg sende dig min API ?

**Comment by MTrab** [comment]
Hehe :D Du kan evt. sende client id og secret til mig på Messenger - bare led efter Morten Trab
