### ISSUE TITLE
Unable to set target temperature via Automation

### ISSUE THREAD

**Issue by Klintrup** [MTrab/danfoss_ally#22]
Integration is installed and seems to be running fine.

Overview card:
- set_temperature works
- current and target temperature displayed correctly
- hvac_mode switching works  (although a bit slow)

Automations (/config/automation/edit)
- current and target temperature can be used as triggers
- hvac mode switching works (manual vs auto) as action
- no options to manually set target temperature as action (same for icon and ally devices)
- Have tried to manually edit yaml and add set_temperature but it won't allow me to save

![ally-issue](https://user-images.githubusercontent.com/18490009/167593181-ed783790-28df-44d2-8d18-5fbf4b6479bc.png)

**Comment by MTrab** [comment]
Totally normal behavior.
You have to call the service Climate: Set temperature

![image](https://user-images.githubusercontent.com/14296463/168465991-a55680ac-eaf3-4f05-9387-6a58826b2ff9.png)
