### ISSUE TITLE
No Integrations

### ISSUE THREAD

**Issue by thorkildnielsen** [MTrab/danfoss_ally#3]
Hi
After installation from HACS it is shown under HACS Integrations, but I cannot find the intergration under Home Assistant > Settings > Integrations

The Homeassistant is rebootet

**Comment by MTrab** [comment]
Check your logs for errors related to this

**Comment by thorkildnielsen** [comment]
Thanks a lot.  After reinstall and reboot same problem.

The logs tell me that is is running but not testet by homeassistant.. 

The integration is still not there.  
![error](https://user-images.githubusercontent.com/72189386/115442323-2a6f9980-a212-11eb-940e-e1fb303cece2.jpg)

**Comment by thorkildnielsen** [comment]
Hi, now the integration is there

Thanks a lot
