### ISSUE TITLE
API errors, Danfoss support not helping

### ISSUE THREAD

**Issue by linuslund123** [MTrab/danfoss_ally#36]
Hi,
I followed all the steps in the SETUP but the integration can't find any of my entities. So I then try to access the entities via the API section of Danfoss developer's page (e.g. https://developer.danfoss.com/docs/ally/1/routes/devices/get), which also fails. The Danfoss support only helps out if you are a "business developer", which I'm not. So a bit of a long shot, but has anyone here ran into the below issues and managed to get around them?

Testing https://developer.danfoss.com/docs/ally/1/routes/devices/get after succesfully authorizing with the API key returns the following
401 Unauthorized
{
  "type": "https://developer.danfoss.com/error-code-reference#unauthorized-internal",
  "title": "Internal authorization error",
  "status": 401,
  "detail": "Unknown email",
  "message_id": "rrt-4812282220058603112-b-geu1-12813-16195259-1"
}

Testing https://developer.danfoss.com/docs/ally/1/routes/users/get returns
404 Not found
{
  "type": "about:blank",
  "title": "Not Found",
  "status": 404,
  "detail": "Error response from target.",
  "message_id": "rrt-4812282220058603112-b-geu1-12813-16195259-4"
}

Finally posting my email to https://developer.danfoss.com/docs/ally/1/routes/users/post (described as Create a user to be used with the Danfoss Ally™ Mobile App.) returns
500 Internal Server Error
{
  "type": "about:blank",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "Error response from target.",
  "message_id": "rrt-4812282220058603112-b-geu1-12813-16195259-5"
}

**Comment by MTrab** [comment]
Unknown email pretty much says it all 🤷🏼‍♀️

**Comment by linuslund123** [comment]
> Unknown email pretty much says it all 🤷🏼‍♀️

It seems to me that the Danfoss service doesn't know about my Danfoss Ally App account, even though it's the same email address for the app and the dev account. Maybe I need to link the app and dev accounts, but can't find out if needed or how do it and support is unhelpful. But if this is only a problem for me I guess I'm out of luck

**Comment by MTrab** [comment]
I don't have Ally myself - only lending access to existing accounts to develop this integration, so sorry - can't be of more help to how you link the dev account to your app account.

**Comment by tcarlsen** [comment]
@linuslund123 I just have same mail and password for both at it works

**Comment by MTrab** [comment]
I've tried to reach out to Danfoss, but as always they are not responding.
I don't find anything in their documentation regarding how to bind the accounts.

**Comment by linuslund123** [comment]
> I've tried to reach out to Danfoss, but as always they are not responding.
They market themselves as being "very conscious about the importance of being open to the world and open to integrate with partners" - but apparently only if you pay above and beyond the cost of the products - very frustrating

**Comment by MTrab** [comment]
Yeah - they are not very supportive at all, on the contrary.

**Comment by Thomas100773** [comment]
I lost access a few days ago, tried a new API just for testing, same issue, unknown email, and its the same as it has been since i bought the damn thermostats and Icon floor heating.
Danfoss support is useless, so for sure the last item i buy from them regarding "smart home" devices.

**Comment by MTrab** [comment]
Wow! Danfoss actually replied to my request for support - it only took them a little over 1 month.
Unfortunately the reply was, freely translated: You are absolutely on your own and we do not want to support an open community and 3rd party developers.

I sent them a friendly but firm reply, that they need to get their shit together and either supply adequate documentation or provide better support for their API if they want their piece of the smart home market.

So sorry guys. Nothing new under the sun.
Just about to archive this repo if they keep their approach against their support.

**Comment by MTrab** [comment]
PS. Please du put pressure on them, my case ID is 11566396 in their Danish customer support system on email kundeservice.dk (at) danfoss.com

**Comment by MTrab** [comment]
Yet another update (they actually CAN be quick if they are tickled the right places)

Got contacted by the eTRV & Business Development product manager requesting some screenshots proving my point. So that have been sent. Perhaps they actually woke up a bit when I wrote that right now I'm actually recommending potential customers to look into other products than Danfoss :D

I'll keep you updated as soon as I hear something

**Comment by MadsGedebuk** [comment]
Great to hear! :)
I have sent now 4 e-mails about the missing support, including refering to your case ID. Maybe everything together has made them wake up :).
I have also pointed out that quite a few people have been recommended to look other ways than Danfoss Ally.

**Comment by MTrab** [comment]
Latest news.
Danfoss technical staff has identified a bug in the API.
They are working on fixing this

**Comment by MTrab** [comment]
Seems like the tech dudes have fixed the errors with the API.
Can we have a confirmation that it's working for you guys now?

**Comment by Thomas100773** [comment]
Working here.

**Comment by linuslund123** [comment]
Here as well! Thanks for chasing them down!
Linus

**Comment by MTrab** [comment]
I'll consider this fixed and close the issue.
I have added to the README a note describing that the email used for the developer account need to be the same as for the app.
