### ISSUE TITLE
Integration has stopped working

### ISSUE THREAD

**Issue by tcarlsen** [MTrab/danfoss_ally#4]
The integration wont set a new temp, and it dont update current set temp if changed on the thermostat it self.

Sadly the log is empty and show no errors

All my entries has no been updated since restart *(a week ago)*
<img width="453" alt="Screenshot 2021-10-06 at 10 08 04" src="https://user-images.githubusercontent.com/145288/136164421-a30074b2-ece5-4619-b4f2-d5fa1b187ad7.png">

My api key is still active

**Comment by MTrab** [comment]
It seems like the problem are situated at Danfoss - I'll reach out to them for further investigation

**Comment by allanedk** [comment]
I'm experiencing the same issue. Did Danfoss respond yet?

PS: Thanks a lot for this integration, @MTrab . I think it would be the perfect solution to be able to interact with the Ally devices through the API instead of bypassing the gateway and connect directly with HA using Zigbee.

**Comment by MTrab** [comment]
Danfoss is, as allways, slower than the slowest snail in the world :/
No, they haven't returned anything usefull.

**Comment by tcarlsen** [comment]
After ally update its working again
