### ISSUE TITLE
Question: for Danfoss Icon systems, does this need the "App module" or the "Zigbee module"?

### ISSUE THREAD

**Issue by Syrah-NL** [MTrab/danfoss_ally#48]
As title: I would like to know if this works with the App module or the Zigbee module of the Icon system. 

And to what extent would I be able to get data from the system to HA? Can I see all the room temperatures? Can I see if the system is heating/cooling or not? For every floor? Can I control the temperatures in the rooms?

Thank you!

**Comment by MTrab** [comment]
The Icon only works thru the Danfoss Ally gateway, if using this integration.

All info and controls should be present
