### ISSUE TITLE
Question: How to go back to Auto mode correctly

### ISSUE THREAD

**Issue by flemminglau** [MTrab/danfoss_ally#49]
I am trying to implement an automated Vacation mode based on everyone being away from the house.

When travelling far away from the house I automatically enter Vacation(Away) mode.

However when returning I have trouble understanding what the right mode should be.
Depending on the automated schedule the house should go to Home (daytime) or Away (nighttime).
But HA should not need to know about the schedule. It should simply go back to "Automated" (i.e. leave it to Ally to select the appropriate mode based on its schedule.)

But as far as I can tell the only modes available from changing out of Vacation(Away) are "Home" or "Away" potentially leaving Ally in the wrong mode until the next scheduled change. What I need is an "Auto according to schedule" mode to change to.

However as far as I can tell when Ally itself is scheduling a Vacation period and you cancel it (or it ends), it automatically ends up in the correct mode as defined in the schedule. 

What am I missing?

Is this question better directed at Danfoss?

**Comment by oveand** [comment]
Did you ever contact Danfoss? And did you find a solution?

**Comment by MTrab** [comment]
I have a Teams meeting with them on Thursday

**Comment by MTrab** [comment]
Currently this is NOT supported - it's in the roadmap, but no ETA for this function

**Comment by flemminglau** [comment]
One can then wonder how the app can do it.

Maybe it looks at the schedule and implements the logic locally in the app.

**Comment by MTrab** [comment]
The app doesn't use the same API as we have available for public use - it's a known issue that the API doesn't always show the same info as the app.
