### ISSUE TITLE
[FR]: Enable groups of thermostats

### ISSUE THREAD

**Issue by chrjoedal** [MTrab/danfoss_ally#65]
When you have a number of thermostats in the same room, the Danfoss Ally app will group them, and only allow you to control the temperature setting for the group, and not for the single thermostats.

This makes more sense, as a room should have the same target temperature. Especially if you, like I have, have multiple thermostats in the same room, along with a room sensor.

I would be nice to have the grouping added, so you from HA can set the target temperature of the group, and not the single thermostats, also to have the same functionality as the Danfoss Ally app.

**Comment by oveand** [comment]
Would be nice, indeed.
Does though seem like not possible with the public APIs provided by Danfoss - https://developer.danfoss.com/catalog/danfoss-ally-api/danfoss-allytm-api#get-/devices
No groups are returned, unfortunately, only devices.

**Comment by MTrab** [comment]
This is currently not possible as the groups are not exposed in the API
