### ISSUE TITLE
Connecting the local Gateway to the developer Account?

### ISSUE THREAD

**Issue by amrheing** [MTrab/danfoss_ally#7]
Hello Morten,
i want to use your integration, but there is a little step I will not found a solution for.

How do I connect my local Ally Gateway to the API App in the developer account?

When trying the Authorize Button on the API Page and give my Account data from the Ally App, I got always an Auth failed :-(

I hope you can help me,

kind regards, and a happy new Year,

Gerald

**Comment by MTrab** [comment]
Everything is mentioned here: https://github.com/MTrab/danfoss_ally#setup

**Comment by amrheing** [comment]
Hi,
After reloading the Integration it is working 

Thanks

Gerald
