### ISSUE TITLE
[FR]: display humidity of sensor 

### ISSUE THREAD

**Issue by Matthieuar** [MTrab/danfoss_ally#77]
Hi, actually we get the temperature and mode, is working well, but it will be nice to get also the humidity . Actually humidity is included in ally 
![IMG_5373](https://github.com/MTrab/danfoss_ally/assets/141206231/ebdd3756-2234-4236-90f6-fb2a96c0c338)

**Comment by MTrab** [comment]
Should be fixed in the current beta release

**Comment by tcarlsen** [comment]
<img width="557" alt="Skærmbillede 2024-02-06 kl  13 18 36" src="https://github.com/MTrab/danfoss_ally/assets/145288/1b679351-1cea-4c68-8b5b-c9cba19ef9c4">

worked before latest version

**Comment by MTrab** [comment]
Did you update to the beta version?

**Comment by tcarlsen** [comment]
im still on 1.2.1, so actually not sure why it stopped working today

**Comment by MTrab** [comment]
API changes - this currently only works in the beta as mentioned in my post just prior to yours ;)
