### ISSUE TITLE
[FR]: Icon2 room temperature sensor is missing a few values in home assistant

### ISSUE THREAD

**Issue by LeetDonkey** [MTrab/danfoss_ally#78]
**Is your feature request related to a problem? Please describe.**
The Icon2 room sensor is able to measure humidity and floor temperature(provided you have the model with IR sensor)
This is reflected in the Danfoss Ally app, but the values are not forwarded to Home Assistant.

**Describe the solution you'd like**
Include humidity and optionally floor temperature in Home Assistant.

**Describe alternatives you've considered**
None

**Additional context**
There are a few other things available as well, for example the setpoint for the floor temperature that may make sense to include as well.
This may be related to the request made here:
https://github.com/MTrab/danfoss_ally/issues/77

But that issue does not look like my Icon2 sensor:

![Screenshot_20230908_144222_Ally](https://github.com/MTrab/danfoss_ally/assets/22496596/799c2dfe-a6e3-4155-b2c6-cd2c6977a4ed)

**Comment by MTrab** [comment]
Should be fixed in the current beta version

**Comment by HologramDK** [comment]
Both floor temperature and humidity is now showing up for my ICON2 thermostats
