### ISSUE TITLE
Set multiple TRV target temperature (Ally group)

### ISSUE THREAD

**Issue by ttlappalainen** [MTrab/danfoss_ally#79]
Ally App contains possibility to group TRV:s within one room. I can not find support for setting Ally group target temperature. If I set individual TRV target temperature - even set to same - Ally App group target temperature does not update.

### Environment:
- Home Assistant version: 2023.09.2
- danfoss_ally version: 1.0.8
- Operation system: HAOS

## Describe the bug
Description on top - maybe not a bug.

**Comment by oveand** [comment]
Seems like duplicate of https://github.com/MTrab/danfoss_ally/issues/65

**Comment by ttlappalainen** [comment]
Yes, thanks. Have to contact Danfoss and request support for groups.

**Comment by MTrab** [comment]
Closing this as it indeed is a duplicate of #65
