### ISSUE TITLE
Requirements for Danfoss Ally not found after update to 1.2.1

### ISSUE THREAD

**Issue by JanSkinnerup** [MTrab/danfoss_ally#80]
After update to 1.2.1 I get these errors:

Logger: homeassistant.setup
Source: setup.py:185
First occurred: 12.12.40 (1 occurrences)
Last logged: 12.12.40

Setup failed for custom integration danfoss_ally: Requirements for danfoss_ally not found: ['pydanfossally==0.0.30'].

and

Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 12.12.14 (3 occurrences)
Last logged: 12.12.40

Unable to install package pydanfossally==0.0.30: ERROR: Could not find a version that satisfies the requirement pydanfossally==0.0.30 (from versions: 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.28, 0.0.29) ERROR: No matching distribution found for pydanfossally==0.0.30

Home assistant install info:
Home Assistant 2023.10.1
Supervisor 2023.10.0
Operating System 10.5
Brugerflade 20231005.0 - latest

**Comment by MTrab** [comment]
Sorry - my bad. Should be fixed now - might take 5 minutes to work though.
Just reload or try again in 5 minutes.
