### ISSUE TITLE
[FR]: Add "Needs attention" to the Device page

### ISSUE THREAD

**Issue by geniodelmale** [MTrab/danfoss_ally#88]
**Is your feature request related to a problem? Please describe.**
When the integration is not working (like during today's API outage) it's difficult to understand that there is a problem.

**Describe the solution you'd like**
Please add a Needs Attention, Failed Setup or another message in the Device list and in the Device page.

**Describe alternatives you've considered**
Nothing that I can think of. Many other integrations display a message in the Device page.

**Additional context**

![image](https://github.com/MTrab/danfoss_ally/assets/22792891/47ea10a4-2046-406b-8b35-4df117692fec)

![image](https://github.com/MTrab/danfoss_ally/assets/22792891/bfb901c6-3e8e-4346-87f7-5c17643ee682)

**Comment by geniodelmale** [comment]
If I reload the integration, even when there's an error, it seems that everything is fine:

![image](https://github.com/MTrab/danfoss_ally/assets/22792891/5f634e22-9720-4a42-999b-f76b256af9f2)

**Comment by preben529** [comment]
It would be nice to know if Danfoss is aware of this issue, and If Danfoss is aware of this sensible setup.

**Comment by MTrab** [comment]
Sorry about the delay, but I really do not understand the issue?! The request (if I read it correct) is for something native Home Assistant and not this integration?!

**Comment by preben529** [comment]
This entry was created when a server at Danfoss was unavailable.

I see the need  to syncronize the ’ally-app’ .

But as danfoss does not see this as a Production-environment, maybe its better to talk to the Ally-components via zigbee/wifi  ?

Best regards
Preben

Fra: Malene ***@***.***>
Sendt: 13. december 2023 08:37
Til: ***@***.***>
Cc: Preben ***@***.***>; ***@***.***>
Emne: Re: [MTrab/danfoss_ally] [FR]: Add "Needs attention" to the Device page (Issue #88)


Sorry about the delay, but I really do not understand the issue?! The request (if I read it correct) is for something native Home Assistant and not this integration?!

**Comment by MTrab** [comment]
Still not sure what you are requesting, as (if I read it correct) everything you have shown is as per design in Home Assistant
