### ISSUE TITLE
Question: Is it possible to use this integration without a Danfoss gateway?

### ISSUE THREAD

**Issue by baskham** [MTrab/danfoss_ally#89]
I have 5 Danfoss Ally TRV's.

I would like to be able to use them without having to buy the rather expensive Danfoss Ally Gateway
.
I am able to add the TRV's to Home Assistant, and I can control them using automation and various Lovelace cards.
But I would really like to be able to use specifically an External temperature sensor and a window switch to control them.

Is this possible without having the Danfoss Ally Gateway?

I am using ZHA.

**Comment by MTrab** [comment]
This integration is for use with the Danfoss gateway only
