### ISSUE TITLE
Valve opening entity missing 

### ISSUE THREAD

**Issue by F-HALD** [MTrab/danfoss_ally#91]
The valve opening entity seems no longer to be supported, or?
It stopped reporting this earlier today.
Same situation for all my Danfoss Ally valves.
![Screenshot_2024-01-30-19-31-42-77_c3a231c25ed346e59462e84656a70e50](https://github.com/MTrab/danfoss_ally/assets/93097830/06b5dfed-7291-4683-aa4f-df9610bb89a7)

**Comment by oveand** [comment]
Seems like pi_heating_demand is not available from API output anymore/right now.
Searching for a changelog.. The current API version is 2.3.0.

**Comment by mbuhansen** [comment]
I also need the valve opening entity, they are gone from all 6 valves. And i use it in some automations.

**Comment by MTrab** [comment]
Any entries in the logfile?

My best guess is that it's because of API changes, but currently I do not have access to the API (I don't use Danfoss myself)

**Comment by geniodelmale** [comment]
I only see messages about deprecated constants.

**Comment by MTrab** [comment]
The API endpoint has been removed. I'm awaiting response from Danfoss as to what we can do to restore this information (if possible)

Any input as for the usecase for this information will be very appreciated

**Comment by chrbast** [comment]
> The API endpoint has been removed. I'm awaiting response from Danfoss as to what we can do to restore this information (if possible)
> 
> Any input as for the usecase for this information will be very appreciated

Det er ret godt til at afgøre om termostaten er blevet tosset og skal nulstilles fordi den så går på 100 pct åben i stedet for “normale” 20-40 pct i min usecase.

**Comment by mbuhansen** [comment]
Jeg bruger værdien som reference, på om radiatoren kan følge med at varme. Hvis thermostat åbner for meget skal vejr kompensering ventil hæves i temperatur.

**Comment by MTrab** [comment]
Should be fixed now ;)

**Comment by F-HALD** [comment]
Perfect, THANKS!
