### ISSUE TITLE
Heating status when it is heating is the inverse value

### ISSUE THREAD

**Issue by ABPaulsen** [MTrab/danfoss_ally#96]
In the beta version v 1.3.0b1 when the system is heating, it shows no heat action. When it is not heating it shows an heat action.

Kontor is NOT heating right now, but shows it:
![image](https://github.com/MTrab/danfoss_ally/assets/121877994/eea26563-9c86-40ee-b979-8fe1c854e401)

and vise versa.

**Comment by MTrab** [comment]
Could you try testing the fix mentioned in https://github.com/MTrab/danfoss_ally/issues/97#issuecomment-1929136432 ?

**Comment by MTrab** [comment]
Will keep the conversation in #97 as there's more info
