### ISSUE TITLE
Termostat cant get external temp in beta

### ISSUE THREAD

**Issue by tcarlsen** [MTrab/danfoss_ally#98]
After updating to beta my the external temp is no longer working and the current temp is set to 25
termostats without a external sensor, shows curret temp

<img width="327" alt="Skærmbillede 2024-02-06 kl  13 39 08" src="https://github.com/MTrab/danfoss_ally/assets/145288/bd305b5e-fbb0-4497-ad0b-41c7426b7cb4">

<img width="588" alt="Skærmbillede 2024-02-06 kl  13 41 24" src="https://github.com/MTrab/danfoss_ally/assets/145288/a0f72dbe-5b24-4ef3-a1e4-f361732a3da1">

**Comment by MTrab** [comment]
The external temperature should be back in the beta version - seems strange it's missing from your sensors

**Comment by tcarlsen** [comment]
<img width="338" alt="Skærmbillede 2024-02-06 kl  13 48 47" src="https://github.com/MTrab/danfoss_ally/assets/145288/80eca55d-7bcc-469c-b188-6642aaa8dba0">
the sensor it self has the temp. but the external sensor temp property on the termostat aint working

**Comment by MTrab** [comment]
Perhaps some of the value matching against the new API makes the external temperature visible as the temperature?!
Need to check that

**Comment by MTrab** [comment]
Fixed in 1.3.0
